## **Правила оценки активности (classwork) для 22ФПЛ-2**  
     


- WIP

# Getting Started with pandas

**Pandas** - библотека для анализа данных, которая предоставляет широкие возможности для работы с табличными данными и временными рядами. Основана на numpy.  
Для работы с данными в библиотеке используются две основные структуры данных - **Series** (для одномерных данных одного типа) и **Data Frame** (для табличных данных вида *наблюдения* $\times$ *признаки*).  
  
У Pandas отличная [документация](http://pandas.pydata.org/pandas-docs/stable/), в которой описывается широкий функционал библиотеки. Обязательно к прочтению [краткое введение](http://pandas.pydata.org/pandas-docs/stable/10min.html).

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

## 1. Welcome, NumPy
NumPy это библиотека для эффективных математических вычислений, обеспечивающая быстроту вычислений, а также сравнительное удобство для работы с матричными операциями (по сравнению со стандартными операциями).

Для старта работы необходимо подключить модуль с библиотекой NumPy:

In [5]:
! pip install numpy # скачать пакеты

In [ ]:
# FYI 
htop in UNIX 

### FYI 
```bash 
htop
```
 in UNIX CPU 

In [4]:
! ls ..

README.md        docs             requirements.txt
data             notebooks        src


In [5]:
import numpy as np

In [6]:
%%timeit

d = list(range(1000000))


37.5 ms ± 5.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%%timeit

d = np.arange(1000000)


1.36 ms ± 167 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
a = [-3,2,1,0,-23,2] # Объявляем список из чисел
t = np.array(a)      # Преобразуем в массив NumPy
t

array([ -3,   2,   1,   0, -23,   2])

In [12]:
type(t)

numpy.ndarray

In [13]:
np.mean(t)

np.float64(-3.5)

Массивы NumPy обладают очень удобным интерфейсом.
Мы можем обращаться непосредственно к массиву, и получать его характеристики. Например, **mean()** - получить среднее значение по массиву.

Функции в составе NumPy обладают очень важным свойством, называемым *векторизацией вычислений*. Если мы передаем в функцию NumPy скалярное значение - она применяет операцию исключительно к этому скаляру.
Рассмотрим, например, функцию взятия абсолютного значения (модуля числа):
* np.abs(x)

И рассмотрим её поведение на скаляре, и на массиве:  
Упомянем основные функции которые мы применяем (или применяли)
* np.abs(x) - вычисляет модуль (абсолютное значение) либо переменной x, либо целого массива - если передан массив.

In [14]:
np.abs(-3)

np.int64(3)

In [15]:
np.abs(t)

array([ 3,  2,  1,  0, 23,  2])

In [16]:
np.exp(t) # применение экспоненциальной функции

array([4.97870684e-02, 7.38905610e+00, 2.71828183e+00, 1.00000000e+00,
       1.02618796e-10, 7.38905610e+00])

Рассмотрим еще несколько функций, которые могут быть полезны:

In [17]:
d = np.array([1, 2, 3, 4])

In [18]:
d

array([1, 2, 3, 4])

**1. Аггрегирование и отклонения**

* **np.min(x)** - поиск минимального элемента в массивве x
* **np.max(x)** - поиск максимального элемента в массиве x
* **np.mean(x)** - среднее значение x
* **np.median(x)** - медиана x
* **np.std(x)** - стандартное отклонение x


Как можно заметить, если обращаться к функции NumPy ```np.min(x)```, то необходимо передавать ей в качестве параметра массив NumPy.
Но есть возможность непосредственно вызвать у массива функцию: ```x.min()```

In [19]:
np.mean(d)

np.float64(2.5)

In [20]:
assert d.mean() == np.mean(d)

In [6]:
assert False

AssertionError: 

**2. Генерация случайных чисел и массивов**

In [ ]:
np.arange(6) # генерирует массив от 0 до переданного ей значения

array([0, 1, 2, 3, 4, 5])

In [21]:
for i in range(5):
    print(i)

0
1
2
3
4


In [22]:
np.arange(3, 6, 2)

array([3, 5])

In [35]:
# np.random.randint(N) - генерирует ОДНО случайное целое число в диапазоне от 0 до N

np.random.randint(5)

4

In [36]:
# Если вы хотите сгенерировать число в диапазоне от K до N (K < N) нужно использовать такой синтаксис:
np.random.randint(5, 10)

7

In [37]:
# Если хотите сгенерировать сразу несколько чисел от K до N  (K<N) нужно использовать сл. формат записи:
np.random.randint(5,10,6)  # Сгенерировать 6 чисел в диапазоне от 5 до 10

array([9, 5, 7, 7, 6, 5])

In [38]:
# np.zeros(N) / np.ones(N) - генерирует массив, матрицу и т.д. из нулей / единиц заданной размерности

np.zeros(4) # вектор

array([0., 0., 0., 0.])

In [40]:
np.ones((2, 2)) # матрица

array([[1., 1.],
       [1., 1.]])

In [41]:
# np.eye(N) - генерирует диагональную матрицу заданной размерности
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**3. Другие операции**

In [42]:
d

array([1, 2, 3, 4])

In [43]:
d.reshape((2, 2)) # изменение размерности (превращаем вектор в матрицу)

array([[1, 2],
       [3, 4]])

In [44]:
d.reshape((2, 2)).T # транспонирование

array([[1, 3],
       [2, 4]])

In [45]:
np.square(d) # квадратичная функция

array([ 1,  4,  9, 16])

In [46]:
matrix = np.ones((3, 2)) + np.ones((3, 2)) # любые арифметические операции (поэлементно), если размерность одинаковая
matrix                                     # или если размерность одной из матриц равняется единице

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [ ]:
matrix.shape

(3, 2)

In [ ]:
matrix + np.array([2, 2]) # OK, т.к. размер вектора (2) = числу столбцов матрицы (2)

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

In [ ]:
np.array([[2],[2]]) # тот же вектор, но в форме столбца

# количество списков внутри array = количество строк матрицы
# количество чисел внутри каждого списка = количество столбцов матрицы

array([[2],
       [2]])

In [ ]:
# matrix + np.array([[2],[2]]) # error!

In [ ]:
np.ones((2, 2)) - np.ones((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
print(d)
print(d.prod()) # умножение элементов

[1 2 3 4]
24


In [ ]:
# matrix.dot(matrix) - умножение матриц / матрицы и вектора

# ЗАДАНИЕ: создать матрицу из десяток ten_matrix и посчитать произведение two_matrix x ten_matrix.

# подсказка 1: матрицу P можно умножить на матрицу K только в том случае, если число столбцов матрицы P равняется числу строк матрицы K.
# подсказка 2: чтобы создать матрицу можно использовать reshape

In [ ]:
two_matrix = np.ones((2, 4)) + np.ones(4)
two_matrix

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
# code

То же, но с [картиночками](https://habr.com/ru/companies/skillfactory/articles/564240/)

## 2. Introduction to pandas Data Structures

Главные структуры Pandas:
* Series
* DataFrame


### Series

Series - одномерный похожий на массив объект, содержащий массив данных **и ассоциированный с им массив меток**, который называется *индексом*.

Простейший объект Series состоит только из массива данных:

In [ ]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

 Поскольку индекс был нами не задан - он сгенерировался по умолчанию - целые числа от $0$ до $N-1$ ($N$ - длина массива).

 Атрибуты values и index объекта Series позволяют соответственно получить массив данных и связанный с ним массив меток.

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

Часто создают Series с индексом, идентифицирующий элемент данных:

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Для выборки одного или нескольких элементов объекта Series можно использовать значения индекса:

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 6 # присвоить новое значение в массиве по индексу

In [ ]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2[['c', 'a', 'd']] # срез массива по индексам

c    3
a   -5
d    6
dtype: int64

Операции с массивом данных, например фильтрация, скалярное умножение или применение математических функций сохраняют взаимосвязь между значением и индексом:

In [ ]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Объект Series можно представлять себе как упорядоченный словарь фиксированной длины - он отображает индекс на данные. И его можно передать функциям, ожидающим на вход словарь.

In [ ]:
'b' in obj2

True

In [ ]:
'e' in obj2

False

По словарю можно создать Series:

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

У Series есть параметр ```index```, которому можно передать на вход список с метками:

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

**3** метки, найденные в ```sdata``` будут помещены в соответствующие позиции. Для метки ```California``` не было никакого значения и ей будет соответствовать признак ```NaN``` (так обозначаются в Pandas отсутствующие значения).

Для распознавания отсутствующих данных следует использовать функции **```isnull```** и **```notnull```**

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Можно вызывать и как методы экземпляра:

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj4.isnull().value_counts()

False    3
True     1
Name: count, dtype: int64

У самого объекта Series и у его индекса есть атрибут name, тесно связанный с другими частями функциональности Pandas:

In [ ]:
obj4.name = 'population'

In [ ]:
obj4.index.name = 'state'

In [ ]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Индекс объекта Series можно менять на месте с помощью присваивания

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### Объект DataFrame

Структура данных Data Frame представляет собой "матрицу" (таблицу), в которой все элементы в одном столбце принадлежат одному типу данных. Типы данных самих столбцов могут различаться.
Такая структура отлично подходит (и была создана) для представления данных типа *наблюдения × признаки*: каждая строчка в data frame соотвествует **наблюдению** (**объекту**), а столбцы содержат **значения признаков**, которыми эти объекты характеризуются.

В объекте DataFrame хранятся два индекса:
* по строкам
* по столбцам

Можно считать, что это словарь объектов Series.

Существует много способов сконструировать объект DataFrame, один из самых распространенных - на основе словаря списков одинаковой длины или массивов NumPy:

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
toy_frame = pd.DataFrame(data)

Для результирующего DataFrame автоматически будет пострен индекс (как и в случае Series), столбцы будут расположены по порядку:

In [ ]:
toy_frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Самый частый способ, которым мы будем пользоваться для создания dataframe на основе файла с данными: **pd.read_csv**

In [ ]:
df = pd.read_csv("telecom_churn.csv")

Метод ```head``` позволяет вывести первые $N$ строк DataFrame:

In [ ]:
df.head(2)

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3                2.7   
1                13.7                 3                3.7   

   Customer service calls  Churn  
0                       1  False  
1                       1  False

При задании последовательности столбцов, столбцы DataFrame расположатся строго в указанном порядке:

In [ ]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
toy_frame.columns

Index(['state', 'year', 'pop'], dtype='object')

Столбец DataFrame можно извлечь как объект Series, воспользовавшись нотацией словарей, или с помощью атрибута:

In [ ]:
toy_frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [ ]:
toy_frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

Возвращенный объект Series имеет тот же индекс, что и DataFrame, а его атрибут name установлен соответствующим образом.

Строки также можно извлечь или по позиции, или по имени. Для этого есть два метода. Один из которых - ```loc``` с указанием индексного поля:

In [ ]:
toy_frame.index = ['one', 'two', 'three', 'four', 'five', 'six']

In [ ]:
toy_frame

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4
five   Nevada  2002  2.9
six    Nevada  2003  3.2

In [ ]:
toy_frame.loc[['three', 'four']]

state  year  pop
three    Ohio  2002  3.6
four   Nevada  2001  2.4

Столбцы можно модифицировать присваиванием. Присвоим одному из столбцов скалярное значение, или массив значений:

In [ ]:
toy_frame['pop'] = toy_frame['pop'].mean()
toy_frame

state  year   pop
one      Ohio  2000  2.55
two      Ohio  2001  2.55
three    Ohio  2002  2.55
four   Nevada  2001  2.55
five   Nevada  2002  2.55
six    Nevada  2003  2.55

In [ ]:
toy_frame['pop'] = np.arange(6.)
toy_frame

state  year  pop
one      Ohio  2000  0.0
two      Ohio  2001  1.0
three    Ohio  2002  2.0
four   Nevada  2001  3.0
five   Nevada  2002  4.0
six    Nevada  2003  5.0

Когда столбцу присваивается список или массив, длина значения должна совпадать с длиной DataFrame. Если присваивается объект Series, то он будет согласован с индексом DataFrame, а напротив отсутствующих индексов будет ```NA```:

In [ ]:
toy_frame['debt'] = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
toy_frame

state  year  pop  debt
one      Ohio  2000  0.0   NaN
two      Ohio  2001  1.0  -1.2
three    Ohio  2002  2.0   NaN
four   Nevada  2001  3.0  -1.5
five   Nevada  2002  4.0  -1.7
six    Nevada  2003  5.0   NaN

Присваивание несуществующему столбцу приведет к его созданию. Для удаления столбцов служит ключевое слово del, как и в обычном словаре Python.

In [ ]:
toy_frame['eastern'] = toy_frame.state == 'Ohio'
toy_frame

state  year  pop  debt  eastern
one      Ohio  2000  0.0   NaN     True
two      Ohio  2001  1.0  -1.2     True
three    Ohio  2002  2.0   NaN     True
four   Nevada  2001  3.0  -1.5    False
five   Nevada  2002  4.0  -1.7    False
six    Nevada  2003  5.0   NaN    False

In [ ]:
del toy_frame['eastern']
toy_frame.columns

Index(['state', 'year', 'pop', 'debt'], dtype='object')

Еще одна распространенная форма данных - словарь словарей. При передаче его в конструктор DataFrame ключи внешнего словаря интерпретируются как столбцы, ключи внутреннего словаря как индексы строк.

In [ ]:
dict_dicts = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [ ]:
toy_frame1 = pd.DataFrame(dict_dicts)
toy_frame1

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

Результаты можно транспонировать:

In [ ]:
toy_frame1.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

Вместо словаря словарей также можно использовать словарь Series

In [ ]:
pdata = {'Ohio': toy_frame1['Ohio'][:-1],
         'Nevada': toy_frame1['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

Атрибут ```values``` возвращает данные хранящиеся в DataFrame в виде двумерного массива:

In [ ]:
toy_frame1.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

### Index Objects (дополнительный материал)

В индесных объектах Pandas хранятся метки вдоль осей и прочие метаданные (например, имена осей). Любой массив или последовательность меток, указанная при конструировании Series или DataFrame преобразуется в объект Index:

In [ ]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index


Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]

Index(['b', 'c'], dtype='object')

Индексные объекты неизменяемы, то есть пользователь не может их модифицировать. И при попытке модифицировать индексный объект **мы получим ошибку**:

In [ ]:
# index[1] = 'd'

Неизменяемость важна для того, чтобы несколько структур могли совместно использовать один и тот же индексный объект, не опасаясь повредить его:

In [ ]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

Индексный объект не только похож на массив, но и ведет себя как множество фиксированного размера:

In [ ]:
toy_frame1

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
toy_frame1.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [ ]:
'Ohio' in toy_frame1.columns

True

In [ ]:
2003 in toy_frame1.index

False

**Задание**: познакомиться с методами и свойствами объекта Index

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 3. Pandas and Series Essential Functionality

Рассмотрим основы взаимодейтвия с данными в объектах Series и DataFrame.

### Reindexing

Для объектов Pandas критически важен метод ```reindex```, т.е. возможность создания нового объекта, данные в котором согласуются с новым индексом. Простой пример:

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

При вызове reindex для этого Series, данные будут реогранизованы в соответствии с новым индексом, а если каких--то из имеющихся в индексе значений не было, вместо них будут подставлены NA:

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

В случае DataFrame функция ```reindex``` может изменять столбцы, строки или и то и другое.

Если ей передать просто последовательность, то в результирующем объекте переиндексируются строки:

In [ ]:
example = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
example

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
example = example.reindex(['a', 'b', 'c', 'd'])
example

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

Для переиндексации столбцов нужно задать ключевое слово columns:

In [ ]:
states = ['Texas', 'Utah', 'California']
example.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping Entries from an Axis

Удалить один или несколько элементов из оси просто, если есть индексный массив или список не содержащий этих значений.

Метод ```drop``` возвращает новый объект, в котором указанные значения исключены из оси:

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

В случае DataFrame указанные в индексе значения можно удалить из любой оси:

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['one', 'two', 'three', 'four'],
                    columns=['Ohio', 'Colorado', 'Utah', 'New York'])
data

Ohio  Colorado  Utah  New York
one       0         1     2         3
two       4         5     6         7
three     8         9    10        11
four     12        13    14        15

In [ ]:
data.drop(['Colorado', 'Ohio'], axis=1) # по умолчанию axis=0 (т.е. удаление производится по строкам)

Utah  New York
one       2         3
two       6         7
three    10        11
four     14        15

In [ ]:
data.drop('two')

Ohio  Colorado  Utah  New York
one       0         1     2         3
three     8         9    10        11
four     12        13    14        15

In [ ]:
data.drop(['Colorado', 'Ohio'], axis='columns')

Utah  New York
one       2         3
two       6         7
three    10        11
four     14        15

In [ ]:
obj.drop('c', inplace=True) # применить изменения к объекту в памяти
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering
Доступ по индексу к объекту Series работает так же как и для массивов NumPy, с отличием, что индексы могут быть любыми значениями из индекса объекта Series, а не только целыми числами:

In [ ]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['b']

1.0

In [ ]:
obj[1] # в дальнейших версиях будет упразднено, необходимо использовать iloc

<ipython-input-105-b9bf7b14fe78>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1] # в дальнейших версиях будет упразднено, необходимо использовать loc


1.0

In [ ]:
obj.iloc[1]

1.0

In [ ]:
obj[2:4] # крайнее значение не включается, как мы и привыкли

c    2.0
d    3.0
dtype: float64

In [ ]:
obj[['b', 'a', 'd']] # просто передать список с индексами строк

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj[[1, 3]] # в дальнейшем будет упразднено, необходимо использовать iloc


<ipython-input-110-c5807766e4fe>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]] # в дальнейшем будет упразднено, необходимо использовать iloc


b    1.0
d    3.0
dtype: float64

Вырезание с помощью меток отличается от обычного вырезания Python тем, что конечная точка **включается**:

In [ ]:
obj['a':'b']

a    0.0
b    1.0
dtype: float64

*Установка* с помощью этих методов работает ожидаемым образом:

In [ ]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

Доступ по индексу к DataFrame применяется для извлечения одного или нескольких столбцов путем задания единственного значения или последовательности:

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two'] # достать столбец = признак (используется ОЧЕНЬ часто)

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [ ]:
data[['three', 'one']] # достать несколько столбцов = признаков

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

У доступа по индексу есть несколько частных случаев. Во-первых, выборка строк с помощью "вырезания" или булева массива:

In [ ]:
data[:2] # конечная точка не включается
# только 0 и 1 объекты

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data[data['three'] > 5]
# только строки, в которых признак three > 5

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Доступ по индексу с помощью булева DataFrame, например, порожденного в результате сравнения

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['one'][data['one'] < 2]
# работаем с Series
# Достать пары "индекс-значение", удовлетворяющие условию

Ohio    0
Name: one, dtype: int64

In [ ]:
data[data['one'] < 2]
# работаем с dataframe
# Достать строки, удовлетворяющие признаковому условию

one  two  three  four
Ohio    0    1      2     3

In [ ]:
data[(data['one'] < 10) & (data['three'] < 10)]
# Условия можно комбинировать
# & - оператор "И"
# | - оператор "ИЛИ"
# Не забываем использовать скобки

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data < 5] = 0

In [ ]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

Для доступа по индексу используется специальный метод **loc** или **iloc**:

In [ ]:
data.loc['Colorado', # строки (названия) / string или list
 ['two', 'three']    # столбцы (названия) / string или list
         ]

# достали одну строку из dataframe
# обратите внимание, что результат представлен в "перевернутом" виде
# из-за того, что мы подали на вход для строк (rows) string

two      5
three    6
Name: Colorado, dtype: int64

In [ ]:
data.loc[['Colorado'], ['two', 'three']]

# так результат выглядит понятнее

two  three
Colorado    5      6

Можно обращаться, указывая конкретные номера строк и столбцов. Например, перепишем пример выше с помощью ``iloc``:

**НЕ ЗАБЫВАЙТЕ, ЧТО ИНДЕКСАЦИЯ НАЧИНАЕТСЯ С НУЛЯ!**

In [ ]:
data.iloc[1,   # столбцы (порядковые индексы) / string или list
         [1,2] # строки (порядковые индексы) / string или list
          ]

# 2-я строка, 2-й и 3-й столбец из dataframe

two      5
three    6
Name: Colorado, dtype: int64

In [ ]:
data.iloc[[1],
          [1,2]
          ]

two  three
Colorado    5      6

In [ ]:
data.iloc[[1],
          [2,1]
          ] # порядок "доставания" можно менять

three  two
Colorado      6    5

Можно обратиться просто к строке Utah:

In [ ]:
data.iloc[2]

# data.iloc[[2]]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [ ]:
data.iloc[1:3] # при слайсинге видим привычную форму

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

Обратите внимание, что если мы обращаемся просто к конкретному(-ым) столбцу(-ам), то необходимо "сказать" Pandas о том, чтобы он использовал все строки.
Для этого следует поставить двоеточие (:), которое предназначено для того, чтобы взять **все элементы**.

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.iloc[:,2]

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int64

Обратимся сразу к нескольким строкам и нескольким столбцам: передадим список с индексами строк, а после запятой список с индексами столбцов.

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

Итак, разница между .loc и .iloc:
* .loc предназначен для доступа по индексу (то что у вас в .index)
* .iloc предназначен для доступа по **номеру** индекса

In [ ]:
data.loc['Utah', 'two']


9

In [ ]:
data.iloc[2,1]

9

Все строки с начала, до 'Utah':

In [ ]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

**Задание**: Воспользовавшись iloc, взять первые три столбца в data и вывести только те строки, где в столбце three значения между 5 и 10.


Подсказка: сначала сделайте первую часть задания, а затем сделайте выборку на основе результата.

In [ ]:
data

# Ваше решение

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Arithmetic and Data Alignment

Одна из самых важных черт Pandas - поведение арифметических операций для объектов с разными индексами. Если при сложении двух объектов обнаруживаются различные пары индексов, то **результирующий индекс будет объединением индексов**.

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

Сложение этих объектов даст:

In [ ]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

Вследствие внутреннего выравнивания данных образуются отсутствующие значения в позициях, для которых **не нашлось соответствующей пары**. Эти отсутствующие значения распространяются на последующие операции.

In [ ]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [ ]:
df2

B
0  3
1  4

In [ ]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values
При выполнении арифметических действий с объектами проиндексированными по разному иногда желательно поместить специальное значение (например 0), в позиции операнда, которым в другом операнде соответствует отсутствующая позиция:

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.loc[1, 'b'] = np.nan

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Сложение этих объектов порождает отсутствующие значения в позициях, которые имеются не в обоих операндах:

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

При вызове  метода ```add``` объекта df1 можно передать объект df2 и значение параметра ```fill_value```:

In [ ]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Точно так же, выполняя переиндексацию объекта Series, или DataFrame можно указать восполняемое значение:

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

Арифметические операции между DataFrame и Series конкретно определены. Рассмотрим вычисление разности между матрицей и одной из ее строк:

In [ ]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

Как  можно увидеть, что из каждой строки вычитается строка. Это называется *укладыванием*.

Операции между DataFrame и Series определяются аналогично:

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

По умолчанию, при выполнении арифметических операций между DataFrame и Series индекс Series сопоставляется со столбцами DataFrame, а укладываются строки:

In [ ]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

Если какой-либо индекс не найдется либо в столбцах DataFrame, либо в индексе Series, то объекты переиндексируются для образования объединения:

In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Если вы хотите сопостовлять строки, а укладывать столбцы, то должны будете воспользоваться каким-нибудь арифметическим методом.

Например:

In [ ]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [ ]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

Передаваемый номер оси - это ось, вдоль которой производится сопоставление.

* 0 - строки
* 1 - столбцы

### Function Application and Mapping

Универсальные функции NumPy (поэлементные методы массивов) отлично работают с объектами Pandas:

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('abc'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

a         b         c
Utah    1.921432  0.165851  1.010563
Ohio    0.851237  0.305536  0.009286
Texas   0.023740  0.362392 -1.323945
Oregon  0.972559 -0.334610  0.410548

In [ ]:
frame = np.abs(frame)
frame

a         b         c
Utah    1.921432  0.165851  1.010563
Ohio    0.851237  0.305536  0.009286
Texas   0.023740  0.362392  1.323945
Oregon  0.972559  0.334610  0.410548

Еще одна часто встречающаяся операция - применение функции, определенной для одномерных массивов к каждой строке или столбцу. Для этого применяется метод ```apply``` объекта DataFrame:

In [ ]:
def f(x):
    return x.max() - x.min()

In [ ]:
frame.apply(f)

a    1.897693
b    0.196541
c    1.314660
dtype: float64

Ту же функцию можно определить lambda функцией:

In [ ]:
f = lambda x: x.max() - x.min()
frame.apply(f)

a    1.897693
b    0.196541
c    1.314660
dtype: float64

Теперь применим ту же функцию, но уже по отношению к столбцам:

In [ ]:
frame.apply(f, axis=1)

Utah      1.755581
Ohio      0.841951
Texas     1.300206
Oregon    0.637949
dtype: float64

**По умолчанию, операции применяются по отношению к строкам, для того, чтобы операции применялись по отношению к столбцам, необходимо явно задавать параметр ```axis=1```**

Многие из наиболее распространенных статистик массивов (например, ```sum``` и ```mean```) - методы DataFrame, поэтому применяеть apply в этом случае необязательно.

In [205]:
frame.sum(axis=1)

Utah      3.097846
Ohio      1.166058
Texas     1.710077
Oregon    1.717717
dtype: float64

Функция передаемая объекту apply не обязана возвращать скалярное значение, она может вернуть и объект Series, содержащий несколько значений:

In [206]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

a         b         c
min  0.023740  0.165851  0.009286
max  1.921432  0.362392  1.323945

Можно использовать и поэлементные функции Python. Допустим, требуется перевести все дробные значения в целые числа. Это позволяет сделать метод ```applymap```:

In [210]:
format = lambda x: int(x)
frame.applymap(format)
# frame.map(format)  # applymap упраздняется, используем просто map

<ipython-input-210-5d16003a25e1>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)


a  b  c
Utah    1  0  1
Ohio    0  0  0
Texas   0  0  1
Oregon  0  0  0

Этот метод называется ```applymap``` поскольку в классе Series уже есть метод ```map``` для применения функции к каждому элементу:

In [211]:
frame['b'].map(format) # теперь также работает и для DataFrame

Utah      0
Ohio      0
Texas     0
Oregon    0
Name: b, dtype: int64

Для замены значений на уровне Series или DataFrame существует метод replace:

In [212]:
frame['b'].map(format).replace(0, 100)

Utah      100
Ohio      100
Texas     100
Oregon    100
Name: b, dtype: int64

In [213]:
frame['a'].map(format)

Utah      1
Ohio      0
Texas     0
Oregon    0
Name: a, dtype: int64

In [214]:
frame['a'].map(format).replace([1, 0], [10, 100]) # можно использовать списки

Utah       10
Ohio      100
Texas     100
Oregon    100
Name: a, dtype: int64

In [216]:
frame.map(format).replace({1: "здесь была 1", 0: "здесь был 0"}) # а можно словарь

a            b             c
Utah    здесь была 1  здесь был 0  здесь была 1
Ohio     здесь был 0  здесь был 0   здесь был 0
Texas    здесь был 0  здесь был 0  здесь была 1
Oregon   здесь был 0  здесь был 0   здесь был 0

### Sorting data

Сортировка набора данных по некоторому критерию  - еще одна важная встроенная операция.

Для лексикографической сортировки по индексу служит метод ```sort_index```, который **возвращает** новый отсортированный объект.

In [217]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

В случае DataFrame сортировку можно проводить по индексу, ассоциированному с **любой осью**:

In [218]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [220]:
frame.sort_index(axis=1) # для сохранения изменений DF необходимо переприсвоить

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [221]:
frame.sort_index(axis=0) # для сохранения изменений DF необходимо переприсвоить

d  a  b  c
one    4  5  6  7
three  0  1  2  3

По умолчанию данные сортируются в порядке возрастания, но их можно отсортировать и в порядке убывания:

In [222]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

Сортировка Series:

In [229]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [230]:
obj.sort_values() # сортировка по значению

2   -3
3    2
0    4
1    7
dtype: int64

In [231]:
obj.sort_index() # сортировка по индексу

0    4
1    7
2   -3
3    2
dtype: int64

По умолчанию отсуствующие значения оказываются в конце Series:

In [232]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [233]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [234]:
obj.sort_values(na_position='first') # поместить отсутствующие в начало

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

Объект DataFrame можно сортировать по значениям в одном или нескольких столбцах. Для этого имена столбцов следует передавать в качестве значения в параметр ```by```

In [235]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [236]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

Сортировка по нескольким столбцам осуществляется передачей списка имён столбцов:

In [237]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

### Axis Indexes with Duplicate Labels. Dealing with Duplicates

До сих пор рассматривались только уникальные метки на осях (значения индекса). Для многих функций Pandas(например ```reindex```) требууется уникальность меток, но в общем случае это необязательно.

Рассмотрим небольшой объект Pandas с повторяющимися значениями в индексе:

In [238]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

О том, являются ли значения уникальными или нет, можно узнав обратившись к методу ```is_unique```:

In [241]:
obj.index.is_unique

False

Выборка данных - одна из основных операций, поведение которых меняется в зависимости от наличия или отсутствия дубликатов. При доступе по индексу, встречающемуся несколько раз, возвращается объект Series.
Если индекс встречается один раз возвращается скалярное значение:

In [242]:
obj['a']

a    0
a    1
dtype: int64

In [243]:
obj['c']

4

Это же правило действует и для доступа к строкам в DataFrame:

In [244]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.274770 -2.699501 -0.387533
a -0.377011 -0.011403  0.763496
b  0.430851 -0.717901 -0.063912
b -0.588943  0.270188 -0.067897

In [245]:
df.loc['b']

0         1         2
b  0.430851 -0.717901 -0.063912
b -0.588943  0.270188 -0.067897

Представим ситуацию, в которой в нашем dataframe затесались строки с дублирующимися индексами. Что мы будем с ними делать?

In [246]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'b', 'b', 'c'])
df

0         1         2
a -0.150622  1.532052  0.107567
b -0.151405  0.357659  1.457213
b  1.520784  0.766834 -1.523401
c -0.512475 -1.353415  0.486850

Если данные напротив индексов уникальны, можно просто провести переиндексацию:

In [247]:
df2 = df.copy()

In [248]:
df2.index = ['a', 'b', 'c', 'd']

In [249]:
df2

0         1         2
a -0.150622  1.532052  0.107567
b -0.151405  0.357659  1.457213
c  1.520784  0.766834 -1.523401
d -0.512475 -1.353415  0.486850

In [250]:
df.reset_index()

index         0         1         2
0     a -0.150622  1.532052  0.107567
1     b -0.151405  0.357659  1.457213
2     b  1.520784  0.766834 -1.523401
3     c -0.512475 -1.353415  0.486850

In [251]:
df.reset_index().drop('index', axis=1)

0         1         2
0 -0.150622  1.532052  0.107567
1 -0.151405  0.357659  1.457213
2  1.520784  0.766834 -1.523401
3 -0.512475 -1.353415  0.486850

Другой вариант: удалить строки с дублирующимися индексами (можно применить, если дубликатов немного и вы не боитесь потерять данные)

In [252]:
df

0         1         2
a -0.150622  1.532052  0.107567
b -0.151405  0.357659  1.457213
b  1.520784  0.766834 -1.523401
c -0.512475 -1.353415  0.486850

In [253]:
df.index.duplicated(keep='first') # буллева маска, True соответствует дубликатам

array([False, False,  True, False])

In [254]:
df[~df.index.duplicated(keep='first')] # тильда обращает False в True и наоборот

0         1         2
a -0.150622  1.532052  0.107567
b -0.151405  0.357659  1.457213
c -0.512475 -1.353415  0.486850

И, наконец, третий вариант - аггрерировать данные по индексу.

In [ ]:
df.groupby(df.index).agg('sum')

0         1         2
a -3.030627 -0.437493 -0.041608
b -2.016067  3.009039 -0.553489
c -1.121747  0.132672 -1.004243

In [ ]:
df.groupby(df.index).agg('max')

0         1         2
a -3.030627 -0.437493 -0.041608
b -0.035807  2.182368  0.290649
c -1.121747  0.132672 -1.004243

## 4. Summarizing and Computing Descriptive Statistics

Объекты Pandas оснащены набором математических и статистических методов. Большая их часть попадает в категорию *редукций* или *сводных статистик* - методов которые вычисляют единственное значение, т.е. скаляр (например, сумму или среднее) для Series и объект Series для строк или столбцов DataFrame.

По сравнению с эквивалентными методами массивов NumPy, все они игнорируют отсутствующие значения:

In [259]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Метод ```sum``` возвращает Series, содержащий суммы по столбцам:

In [260]:
df.sum()

one    9.25
two   -5.80
dtype: float64

При передаче параметра ```axis=1``` суммирование будет производиться по строкам:

In [261]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

Отсутствующие значения исключаются, если только не является отсутствующим весь срез (строка или столбец). Это можно подавить, задав параметр ```skipna```:

In [262]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

Параметры:
* axis - ось по которой производится редуцирование. В случае DataFrame 0 означает строки, 1 столбцы;
* skipna - исключать отсутствующие значения. По умолчанию True

Некоторые методы, например ```idmin``` и ```idmax``` возвращают косвенные статистики, например, индекс на котором достигается максимум или минимум:

In [263]:
df.idxmax()

one    b
two    d
dtype: object

Также есть аккумулирующие методы:

In [264]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

Существуют методы не относящиеся ни к редуцирующим, ни к аккумулирующим.

Примером может служить метод ```describe```, возвращающий несколько сводных статистик за одно обращение:

In [265]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

В сучае нечисловых данных, ```describe``` возвращает и другие сводные статистики:

In [266]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [267]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

Описательные и сводные статистики:
 * ```count``` - количество значений, исключая отсутствующие
 * ```describe``` - вычисляет набор сводных статистик для Series или для каждого столбца DataFrame
 * ```min, max``` - минимальное или максимальное значения
 * ```argmin, argmax``` - вычисляет позицию в виде индекса (целого числа) при котором достигается минимальное или максимальное значения соответственно
 * ```idxmin, idxmax``` - вычисляет значение индекса, при котором достигается минимальное или максимальное значение соответственно
 * ```quantile``` - вычисляет выборочный квантиль в диапазоне от 0 до 1
 * ```sum``` - сумма
 * ```mean``` - математическое ожидание (среднее)
 * ```median``` - медиана
 * ```mad``` - среднее отклонение от среднего
 * ```var```- выборочная дисперсия
 * ```std``` - выборочное стандартное отконение
 * ```skew``` - асимметрия


In [268]:
df = pd.DataFrame(np.arange(36).reshape(6, 6), columns=['one', 'two', 'three', 'four', 'five', 'six'])
df

one  two  three  four  five  six
0    0    1      2     3     4    5
1    6    7      8     9    10   11
2   12   13     14    15    16   17
3   18   19     20    21    22   23
4   24   25     26    27    28   29
5   30   31     32    33    34   35

In [269]:
df['one'].median()

15.0

In [270]:
df['one'].quantile(0.9)

27.0

In [271]:
df['one'].std()

11.224972160321824

### Unique Values, Value Counts, and Membership

Еще один класс методов служит для извелечения информации о значениях, хранящихся в одномерном объекте Series. Для иллюстрации рассмотрим пример:

In [272]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

Метод ```unique``` возвращает массив уникальных значений в Series:

In [273]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [274]:
uniques = np.array(list(set(obj))).astype('object') # аналогичная операция, но без unique
uniques

array(['a', 'c', 'b', 'd'], dtype=object)

Уникальные значения необязательно возвращаются в отсортированном порядке, но могут быть отсортированы впоследствии если это необходимо (```np.sort()```). Метод ```value_counts()``` вычисляет объект Series, содержащий частоты встречаемости значений:

In [275]:
obj.value_counts() # 100% пригодится для анализа категориальных признаков

c    3
a    3
b    2
d    1
Name: count, dtype: int64

Функция ```value_counts``` может быть вызывана как метод, и в таком случае применима к **любому массиву или последовательности**

In [276]:
pd.value_counts(obj.values, sort=False)

<ipython-input-276-e257afe01fc8>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

Метод ```isin``` вычисляет булев вектор членства в множестве и полезен для фильтрации набора данных относительно подмножества значений в объекте Series или столбце DataFrame:

In [277]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [278]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [279]:
obj[mask] # убери все, кроме c и b

0    c
5    b
6    b
7    c
8    c
dtype: object

In [280]:
obj[~mask] # оставь все, кроме c и b

1    a
2    d
3    a
4    a
dtype: object

Итак,

* ```isin``` вычисляет булев массив, показывающий, содержится ли каждое принадлежащее Series значение в переданной последовательности;
* ```unique``` вычисляет массив уникальных значений в Series и возвращает их в порядке появления
* ```value_counts``` возвращает объект Series который содержит уникальное значение (как индекс) и его частоту (как значение). Отсортирован в порядке убывания частот.

Большую часть функций, которые мы рассмотрели в данном уроке, вы вряд ли будете часто использовать.  
  
Самое важное:  
- Понимать устройство Series и DataFrame  
- Уметь делать выборку строк и столбцов в DataFrame  
- Уметь получать статистики по признакам (Series) в DataFrame  
- Применять к столбцам и строкам Dataframe различные функции.  
- Анализировать и редактировать Dataframe и Series, используя только методы, предусмотренные numpy и pandas.  